### ISSUE TITLE
I need basic command lines

### ISSUE THREAD

**Issue by p0stm0rt3m** [click2install/elleriumcoin#1]
How can i log in using my generated username and my generated password? Every time i try to use the command line to access the information it say: Permission denied

How can i retrieve my masternode private key if generated with the scypt while loading the wallet? 

What is the command line to erase everything and start all over again. I do not want to leave 2 masternodes configs on the network without using them.

Thank you!

**Comment by click2install** [comment]
- The username and password are presented as output once the script runs, you should copy/paste this to your local PC for safe keep. The node is deliberately installed to a user account for security and also ease of removal
 - To reset the password you can `passwd <username>` if you did not make a note of it when the script ran. The generated password are deliberately strong
 - To switch to the user you can use `su - <username>` but you may need to know its password, unless you `su` from the root user
 - To retrieve your privkey you can use `cat /home/<username>/.ellerium/ellerium.conf` do not share this information though, as your private key should not be known by anyone
 - To list all the users that have been created use `ls -al /home` to see their home folders
 - To remove a users masternode use `userdel -r <username>`, all the configuration for each user masternode is installed to the users home folder and this command will remove the user and its home directory
