### ISSUE TITLE
privkey is empty

### ISSUE THREAD

**Issue by truonghoangnguyen** [click2install/elleriumcoin#2]
privkey is empty (when not input privkey on install):

![image](https://user-images.githubusercontent.com/1657877/42563304-1e4cb6b0-8528-11e8-974a-054c937bd5f6.png)

**Comment by click2install** [comment]
I am going to need some repro details if I have any chance of fixing or understanding how this can come about. Many people use this script without issue, so I suspect it is environmental. Generally, if the script has some issue and it cannot start the master node the first time to request the privkey, it will be empty - but that will result in an error during execution and will be shown before the script finishes. Were you able to verify there was no privkey in the generated config file?

**Comment by truonghoangnguyen** [comment]
I have workaround by manual enter privkey, 

> Were you able to verify there was no privkey in the generated config file?  

Tech me how to do this ?

**Comment by click2install** [comment]
run this from your VPS but do not show anyone the output as it will [should] contain your privkey `cat ~/home/<username>/.ellerium/ellerium.conf` where you will replace `<username>` with the username you installed your masternode with when the script asked you.
